### ISSUE TITLE
Localized interface

### ISSUE THREAD

**Issue by i3visio** [Nakiami/mellivora#40] opened 2015-03-15 17:53 UTC
We were trying to translate the interface to Spanish but there are some issues that imply rewriting too much code making updates being crazy. Although we have translated the whole interface to Spanish, we feel it would be interesting to upload those texts onto some sort of .xml files to let the language be selected by the user in their profile page for instance. Is anyone working on something similar?

**Comment by SEV007** [comment] 2015-08-28 02:25
Actually we were looking to do some change with Whihax and Hexa Shark members. Next month we have 3 days CTF at Valencia, Spain so we found thes Score board which is exciting, but it looks like you will need to find all the text parts to make the change. Now we are trying to make the Score Board Dynamic with Jquery.

**Comment by i3visio** [comment] 2015-08-29 21:45
We've been working on a literal translation of the interface but seems to be buggy if you translate "too much"... The point is that it would not be scalable when any additional changes are done to the English interface. :S

**Comment by SEV007** [comment] 2015-08-30 13:50
For being a free code is enough. Now I only need to use Ajax for dynamic scoreboard updates.

-----Mensaje original-----
De: "i3visio" <notifications@github.com>
Enviado: ‎29/‎08/‎2015 23:45
Para: "Nakiami/mellivora" <mellivora@noreply.github.com>
CC: "Deus" <deus2323@gmail.com>
Asunto: Re: [mellivora] Localized interface (#40)

We've been working on a literal translation of the interface but seems to be buggy if you translate "too much"... The point is that it would not be scalable when any additional changes are done to the English interface. :S

**Comment by i3visio** [comment] 2015-08-30 13:54
If you needed help with testing that code, let us be informed. I'll check the state of our translations anyway.

**Comment by SEV007** [comment] 2015-08-30 14:23
I think I won't need help for testing as a friend put it in a own server and we make everything on the fly. Thanks! But if we succeed we may try to share the changes over here. We are still unsure how to deal with the function calls as mellivora's purpose is to be static (which is not a good idea for the scoreboard part, but is the best scoreboard we could find out there)

-----Mensaje original-----
De: "i3visio" <notifications@github.com>
Enviado: ‎30/‎08/‎2015 15:54
Para: "Nakiami/mellivora" <mellivora@noreply.github.com>
CC: "Deus" <deus2323@gmail.com>
Asunto: Re: [mellivora] Localized interface (#40)

If you needed help with testing that code, let us be informed. I'll check the state of our translations anyway.

**Comment by Nakiami** [comment] 2015-09-06 07:02
Working on multilang branch here: https://github.com/Nakiami/mellivora/tree/multilang_support

**Comment by SEV007** [comment] 2015-09-06 15:11
Did you solved the category change problem at the challenges section?

-----Mensaje original-----
De: "Nakiami" <notifications@github.com>
Enviado: ‎06/‎09/‎2015 9:02
Para: "Nakiami/mellivora" <mellivora@noreply.github.com>
CC: "Deus" <deus2323@gmail.com>
Asunto: Re: [mellivora] Localized interface (#40)

Working on multilang branch here: https://github.com/Nakiami/mellivora/tree/multilang_support

**Comment by Nakiami** [comment] 2015-09-07 03:59
Which problem is that?

**Comment by SEV007** [comment] 2015-09-07 10:36
The problem when multiple categories ate created and you try tu visualize them at challenges section and Chang between them to read the description. There was some message like wrong or non existing category Id caused by deprecated PHP function. Or may be our server is shitty no t sure...

-----Mensaje original-----
De: "Nakiami" <notifications@github.com>
Enviado: ‎07/‎09/‎2015 5:59
Para: "Nakiami/mellivora" <mellivora@noreply.github.com>
CC: "Deus" <deus2323@gmail.com>
Asunto: Re: [mellivora] Localized interface (#40)

Which problem is that?

**Comment by SEV007** [comment] 2015-09-10 14:33
Hmm I'm not sure if I did it right but I created a Fork of Mellivora and then Pulled a Request and Merged it with the changed Challanges.php changing the way the assosiative array is addressed by the php function. Sorry if I'm doing it wrong, I'm new at github.

**Comment by Nakiami** [comment] 2015-09-27 07:40
Merged to master as part of https://github.com/Nakiami/mellivora/pull/52

**Closed by Nakiami** 2015-09-27 07:40 UTC
